kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: neuvector
  namespace: fleet-default
spec:
  repo: https://github.com/bgregorius-rgs/fleet-security-demo.git
  branch: main
  targets:
  - clusterGroup: secured
  paths:
  - "./neuvector/crd"
  - "./neuvector/core"
