global:
  cattle:
    url: https://shift5-ra-ranchere-j01v1j1e2613-937372100.us-east-1.elb.amazonaws.com/

docker:
  enabled: false
k3s:
  enabled: true
controller:
  ranchersso:
    enabled: true

crdwebhook:
  enabled: false